[section#uncaught.exceptions
    [:en] [`uncaught_exceptions]
    [:zh_CN] [`uncaught_exceptions]
]

[%@lib uncaught_exceptions]
[codeblock:declaration]
constexpr int uncaught_exceptions() noexcept;
[codeblock:end]

[div:description]
[para:returns]
[:en] The number of uncaught exceptions ([#except.throw]) in the current thread.
[:zh_CN] 当前线程中未捕获的异常的数量（[#except.throw]）。

[para:remarks]
[:en] When [`uncaught_exceptions() > 0], throwing an exception can result in a
call of the function [`std::terminate] ([#except.terminate]).
[:zh_CN] 当 [`uncaught_exceptions() > 0] 时，抛出异常将导致调用函数
[`std::terminate]（[#except.terminate]）。
[div:end]
