[section#except.special.general
    [:en] General
    [:zh_CN] 概述
]

[para]
[:en] The function [`std::terminate] ([#except.terminate]) is used by the exception
handling mechanism for coping with errors related to the exception handling
mechanism itself.
[:zh_CN] 异常处理机制利用函数 [`std::terminate]（[#except.terminate]）以应付与
异常处理机制自身相关的错误。

[:en] The function [`std::uncaught_exceptions] ([#uncaught.exceptions])
reports how many exceptions are uncaught in the current thread.
[:zh_CN] 函数 [`std::uncaught_exceptions]（[#uncaught.exceptions]）报告当前线程
中有多少未捕获异常。

[:en] The function [`std::current_exception] ([#propagation]) and the class
[`std::nested_exception] ([#except.nested]) can be used by a program to capture
the currently handled exception.
[:zh_CN] 程序可以利用函数 [`std::current_exception]（[#propagation]）和类
[`std::nested_exception]（[#except.nested]）来获得当前被处理的异常。
